import type { Metadata } from "next";
import "./globals.css";
import MainContainer from "./components/MainContainer";

export const metadata: Metadata = {
  title: "Store Dev",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <MainContainer>

          {children}
        </MainContainer>
      </body>
    </html>
  );
}
